---
- name: debian | installing ZFS
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - linux-headers-amd64
     - zfs-dkms
     - zfsutils-linux

- name: debian | enabling zfs module
  modprobe:
    name: zfs
    state: present

# Note: iscsitarget needs refactoring for working on debian 9
# https://www.hiroom2.com/2017/07/11/debian-9-tgt-en/

- name: debian | installing iscsitarget (if enabled)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsitarget
    - iscsitarget-dkms
  when: >
        zfs_enable_iscsi is defined and
        zfs_enable_iscsi

- name: debian | un-installing iscsitarget (if not enabled)
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - iscsitarget
    - iscsitarget-dkms
  when: >
        zfs_enable_iscsi is defined and
        not zfs_enable_iscsi

- name: debian | configuring iscsitarget service
  template:
    src: etc/default/iscsitarget.j2
    dest: /etc/default/iscsitarget
    owner: root
    group: root
    mode: 0644
  notify:
    - restart iscsitarget
  when: >
        zfs_enable_iscsi is defined and
        zfs_enable_iscsi

- name: debian | installing NFS (if enabled)
  apt:
    name: nfs-kernel-server
    state: present
  when: >
        zfs_enable_nfs is defined and
        zfs_enable_nfs

- name: debian | un-installing NFS (if not enabled)
  apt:
    name: nfs-kernel-server
    state: absent
  when: >
        zfs_enable_nfs is defined and
        not zfs_enable_nfs

- name: debian | configuring NFS Kernel Server
  template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nfs-kernel-server
    - start zfs-share
  when: >
        zfs_enable_nfs is defined and
        zfs_enable_nfs

- name: debian | configuring ZFS
  template:
    src: etc/default/zfs.j2
    dest: /etc/default/zfs
    owner: root
    group: root
    mode: 0644
  notify:
    - start zfs-share
